#pragma once

#include "../Shared/GameCommon.h"
#include "../Shared/Protocol.h"
#include "../Shared/Runtime/CoreMacro.h"
#include "../Shared/Runtime/CoreTLS.h"
#include "../Shared/Runtime/GameTimer.h"
#include "../Shared/Runtime/NetworkPlatform.h"

#include <algorithm>
#include <array>
#include <atomic>
#include <bcrypt.h>
#include <chrono>
#include <cstdint>
#include <cstdlib>
#include <cstring>
#include <iostream>
#include <map>
#include <memory>
#include <mutex>
#include <queue>
#include <set>
#include <shared_mutex>
#include <stdexcept>
#include <string>
#include <thread>
#include <unordered_map>
#include <utility>
#include <vector>
